# admin : admin. Password hash is Digest::MD5.hexdigest(password + salt). Salt should be very very random
# Uploader key is any somewhat secret string you want, like ActiveSupport::SecureRandom.hex(16). Don't use a real password since it is transmitted in plain text.
login: admin
salt: "2zyu88yzld60ae9f"
password_hash: "303d9d679dc385dc5f7ca206659f10ba"
uploader_key: ""
image_dimensions: "1024x1024>"
